openapi: 3.0.0
x-stoplight:
  id: f4gjmz7iq821u
info:
  title: ConnectModule Configuration API
  version: 1.1.0
  description: |-
    The ConnectModule test22 API empowers you to manage your portfolio of Bosch ConnectModules (BCM) via a convenient web 
    interface.
    BCM devices are enabled for remote configuration by default with software version `BES3_12` and above. To use latest
    features, keep the BCM updated with the latest BES3 releases.    

    #### Supported operations

    - Discover ConnectModule identifiers
    - Claim and waive permissions to manage a ConnectModule
    - Enable and disable features of ConnectModules you own
  contact:
    email: cloud-api.support@de.bosch.com
    name: Bosch eBike Systems Support
servers:
  - description: Production
    url: 'https://api.bosch-ebike.com/connect-module/v1'
security:
  - Client: []
tags:
  - name: ConnectModule Discovery
  - name: ConnectModule Ownerships
  - name: ConnectModule Configurations
paths:
  '/connect-module-masters/{id}':
    get:
      deprecated: true
      summary: Retrieve master data of a bike with installed ConnectModule
      description: |
        Deprecation notice: we are phasing out the possibility to query master data using `OEM_BIKE_ID` query parameter 
        type. The option to query using `OEM_BIKE_ID` will be sunset on 31.12.2025. Please adapt to use the unique Bosch
        system ID from that point onwards. Versions `v2` and up of this API will support `bikeId` as query parameter 
        only.

        Returns identifier data of a bike with installed ConnectModule if it belongs to the authenticated client or 
        has no owner. 

        **Note:** Since the `OEM_BIKE_ID` does not represent a unique identifier, the service may respond with 
        `404 - Not Found` if `idType=OEM_BIKE_ID` is used, although the system exists. Problem instance will be 
        `/problems/resource-not-found#ambiguous-identifier`. Please disambiguate by issuing the request using the Bosch 
        system ID ( `BIKE_ID` ).
      tags:
        - ConnectModule Discovery
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: idType
          description: Type of identifier used. One of `BIKE_ID` or `OEM_BIKE_ID`.
          required: false
          deprecated: true
          schema:
            type: string
            default: BIKE_ID
            enum:
              - BIKE_ID
              - OEM_BIKE_ID
      responses:
        '200':
          description: OK
          headers:
            Deprecation:
              description: UTC time when deprecation was announced
              schema:
                type: string
              example: '@1756677600'
            Sunset:
              description: Timestamp when endpoint will no longer be available
              schema:
                type: string
              example: 'Sun, 31 Dec 2025 23:59:59 GMT'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectModuleMaster'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      operationId: get-connect-module-master-id
      security:
        - Client:
            - 'bcm:configuration:write'
      x-stoplight:
        id: nxitgluumhyf4
  /connect-modules:
    get:
      summary: List all ConnectModules
      tags:
        - ConnectModule Configurations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                  - connectModules
                properties:
                  connectModules:
                    type: array
                    items:
                      $ref: '#/components/schemas/ConnectModule'
              example:
                connectModules:
                  - id: BCM3100_EB1310000B_17918-0052-01-368-00-0000
                    bikeId: 7255dccf-c929-41f7-9aa6-a043f6096e19
                    oemBikeId: ZMFPKXJ9Y6ZRSTW4
                    oemBrandId: YOUR-BRAND
                    createdAt: '2023-03-01T14:31:00.002Z'
                    updatedAt: '2023-03-05T14:31:00.002Z'
                    syncedAt: '2019-08-24T14:15:22Z'
                    syncStatus: SUCCESS
                    features:
                      - type: LOCATION_TRACKING
                        status: ENABLED
                        updatedAt: '2023-06-29T14:39:00.002Z'
                        requestedProfile: DEFAULT
                        appliedProfile: DEFAULT
                      - type: BIKE_STATUS
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                      - type: DISABLE_MOTOR_SUPPORT
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      operationId: get-connect-modules
      security:
        - Client:
            - 'bcm:configuration:write'
      description: Returns a list of all ConnectModules belonging to the authenticated client.
      x-stoplight:
        id: m4azswfmqpdvo
  '/connect-modules/{moduleId}':
    parameters:
      - $ref: '#/components/parameters/moduleId'
    get:
      summary: Retrieve a single ConnectModule
      tags:
        - ConnectModule Configurations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectModule'
              examples:
                All features disabled:
                  value:
                    id: BCM3100_EB1310000B_17918-0052-01-368-00-0000
                    bikeId: 7255dccf-c929-41f7-9aa6-a043f6096e19
                    oemBikeId: ZMFPKXJ9Y6ZRSTW4
                    oemBrandId: YOUR-BRAND
                    createdAt: '2023-06-29T14:31:00.002Z'
                    updatedAt: '2023-06-29T14:31:00.002Z'
                    syncedAt: '2023-06-29T14:35:00.002Z'
                    syncStatus: SUCCESS
                    features:
                      - type: LOCATION_TRACKING
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                      - type: BIKE_STATUS
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                      - type: DISABLE_MOTOR_SUPPORT
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                LocationTracking pending:
                  value:
                    id: BCM3100_EB1310000B_17918-0052-01-368-00-0000
                    bikeId: 7255dccf-c929-41f7-9aa6-a043f6096e19
                    oemBikeId: ZMFPKXJ9Y6ZRSTW4
                    oemBrandId: YOUR-BRAND
                    createdAt: '2023-06-29T14:31:00.002Z'
                    updatedAt: '2023-06-29T14:39:00.002Z'
                    syncedAt: '2023-06-29T14:35:00.002Z'
                    syncStatus: PENDING
                    features:
                      - type: LOCATION_TRACKING
                        status: PENDING
                        updatedAt: '2023-06-29T14:39:00.002Z'
                        requestedProfile: DEFAULT
                        appliedProfile: NONE
                      - type: BIKE_STATUS
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                      - type: DISABLE_MOTOR_SUPPORT
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                LocationTracking enabled:
                  value:
                    id: BCM3100_EB1310000B_17918-0052-01-368-00-0000
                    bikeId: 7255dccf-c929-41f7-9aa6-a043f6096e19
                    oemBikeId: ZMFPKXJ9Y6ZRSTW4
                    oemBrandId: YOUR-BRAND
                    createdAt: '2023-06-29T14:31:00.002Z'
                    updatedAt: '2023-06-29T14:39:00.002Z'
                    syncedAt: '2023-06-29T14:40:00.002Z'
                    syncStatus: SUCCESS
                    features:
                      - type: LOCATION_TRACKING
                        status: ENABLED
                        updatedAt: '2023-06-29T14:39:00.002Z'
                        requestedProfile: DEFAULT
                        appliedProfile: DEFAULT
                      - type: BIKE_STATUS
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                      - type: DISABLE_MOTOR_SUPPORT
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                LocationTracking enabled warning:
                  value:
                    id: BCM3100_EB1310000B_17918-0052-01-368-00-0000
                    bikeId: 7255dccf-c929-41f7-9aa6-a043f6096e19
                    oemBikeId: ZMFPKXJ9Y6ZRSTW4
                    oemBrandId: YOUR-BRAND
                    createdAt: '2023-06-29T14:31:00.002Z'
                    updatedAt: '2023-06-29T14:39:00.002Z'
                    syncedAt: '2023-06-29T14:40:00.002Z'
                    syncStatus: WARNING
                    features:
                      - type: LOCATION_TRACKING
                        status: ENABLED
                        statusDetail:
                          type: WARNING
                        updatedAt: '2023-06-29T14:39:00.002Z'
                        requestedProfile: DEFAULT
                        appliedProfile: DEFAULT
                      - type: BIKE_STATUS
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                      - type: DISABLE_MOTOR_SUPPORT
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                LocationTracking disabled warning:
                  value:
                    id: BCM3100_EB1310000B_17918-0052-01-368-00-0000
                    bikeId: 7255dccf-c929-41f7-9aa6-a043f6096e19
                    oemBikeId: ZMFPKXJ9Y6ZRSTW4
                    oemBrandId: YOUR-BRAND
                    createdAt: '2023-06-29T14:31:00.002Z'
                    updatedAt: '2023-06-29T14:39:00.002Z'
                    syncedAt: '2023-06-29T14:40:00.002Z'
                    syncStatus: WARNING
                    features:
                      - type: LOCATION_TRACKING
                        status: DISABLED
                        statusDetail:
                          type: WARNING
                        updatedAt: '2023-06-29T14:39:00.002Z'
                        requestedProfile: DEFAULT
                        appliedProfile: DEFAULT
                      - type: BIKE_STATUS
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                      - type: DISABLE_MOTOR_SUPPORT
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                LocationTracking disabled error:
                  value:
                    id: BCM3100_EB1310000B_17918-0052-01-368-00-0000
                    bikeId: 7255dccf-c929-41f7-9aa6-a043f6096e19
                    oemBikeId: ZMFPKXJ9Y6ZRSTW4
                    oemBrandId: YOUR-BRAND
                    createdAt: '2023-06-29T14:31:00.002Z'
                    updatedAt: '2023-06-29T14:39:00.002Z'
                    syncedAt: '2023-06-29T14:40:00.002Z'
                    syncStatus: ERROR
                    features:
                      - type: LOCATION_TRACKING
                        status: DISABLED
                        statusDetail:
                          type: ERROR
                        updatedAt: '2023-06-29T14:39:00.002Z'
                        requestedProfile: DEFAULT
                        appliedProfile: DEFAULT
                      - type: BIKE_STATUS
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
                      - type: DISABLE_MOTOR_SUPPORT
                        status: DISABLED
                        updatedAt: '2023-06-29T14:31:00.002Z'
                        requestedProfile: NONE
                        appliedProfile: NONE
          headers:
            ETag:
              schema:
                type: string
              description: Calculated value to check with the `If-None-Match` request header  if the resource has changed.
        '304':
          description: Not Modified
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      operationId: get-connect-modules-moduleId
      description: |-
        Returns detailed information of a ConnectModule belonging to the authenticated client.

        This endpoint supports `ETag` (entity tag), a HTTP response header, to check if the resource has changed.
        ETags can be used by API clients for caching and conditional requests to save bandwidth by using the `If-None-Match` HTTP request header.
      parameters:
        - schema:
            type: string
          in: header
          name: If-None-Match
          description: 'Use the value of the previously received ETag response header to check if the resource has changed. If so, you get the HTTP response status `200`, the current version of the resource and a new ETag response header. In case the resource has not changed you just get the HTTP response status `304`.'
      security:
        - Client:
            - 'bcm:configuration:write'
      x-stoplight:
        id: wc7f8d65wijxp
  '/connect-modules/{moduleId}/features/{featureType}':
    parameters:
      - $ref: '#/components/parameters/moduleId'
      - schema:
          type: string
          x-extensible-enum:
            - value: LOCATION_TRACKING
            - value: BIKE_STATUS
            - value: DISABLE_MOTOR_SUPPORT
        name: featureType
        in: path
        required: true
        description: Type of feature.
    put:
      summary: Configure a ConnectModule feature
      operationId: put-connect-module-feature
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feature'
              examples:
                Example 1:
                  value:
                    type: LOCATION_TRACKING
                    status: PENDING
                    updatedAt: '2019-08-24T14:15:22Z'
                    requestedProfile: DEFAULT
                    appliedProfile: NONE
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      tags:
        - ConnectModule Configurations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feature'
      security:
        - Client:
            - 'bcm:configuration:write'
      description: |
        Use this operation to enable or disable a ConnectModule feature.

        You must select for each feature a predefined profile in order to control the collection and transmission rate of the data sent from the BCM to the Bosch cloud. Each feature provides at least the profiles `DEFAULT` and `NONE`. Features can also provide additional profiles.

        The following table explains the feature profiles in detail:

        | Feature      | Profile      | Description      | Immediate Triggers to send data     | Intervall to send data |
        | :---        | :---        | :---        | :---        |    :----   |
        | BIKE_STATUS      | DEFAULT      | Use this profile to send data during eBike usage      | <ul><li>eBike turned on/off</li><li>Charger connected/disconnected</li><li>Charging starts/stops</li><li>BCM needs charge/charge critical</li></ul> | <ul><li>Every 4 minutes if eBike is on and moving</li><li>Every 4 minutes while charger is connected and eBike is charging</li><li>Every 24 hours</li></ul> |
        | BIKE_STATUS      | CHARGING   |   Optimized profile for eBike state of charge      | <ul><li>eBike turned on/off</li><li>Charger connected/disconnected</li><li>Charging starts/stops</li><li>BCM needs charge/charge critical</li></ul> | <ul><li>Every 6 minutes while charger is connected and eBike is charging</li><li>Every 24 hours</li></ul> |
        | LOCATION_TRACKING      | DEFAULT   |   Use this profile to send data during eBike motion      | N/A      | <ul><li>Every 4 minutes if eBike is moving and BCM charge state is not critical</li><li>Every 24 hours</li></ul> |
        | DISABLE_MOTOR_SUPPORT | DEFAULT | Use this profile to remotely disable motor support | <ul><li>eBike turned on/off</li></ul> | N/A |
        | **any**      | NONE      | Disables the feature      | N/A      | N/A        |

        Configuration updates will set the feature syncStatus first to `PENDING`. With the next eBike *power-on*, the BCM requests the latest configuration, applies it and sends a confirmation back to the Bosch cloud. The feature syncStatus will be `SUCCESS` in case of success. There is also a status for `WARNING` and `ERROR`.

        Once a feature is enabled the BCM starts sending data according to the configured profile.
      x-stoplight:
        id: sjwo08ttq8zup
  /ownerships:
    post:
      deprecated: true
      summary: Claim ConnectModule ownership
      operationId: post-ownership
      description: |
        Claim ownership of a ConnectModule providing the `moduleId` and `bikeId` as request body.
        The system must first be registered in our backend. This happens automatically on first system start up.
      tags:
        - ConnectModule Ownerships
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectModuleMaster'
      responses:
        '200':
          description: OK
          headers:
            Deprecation:
              description: UTC time when deprecation was announced
              schema:
                type: string
              example: '@1756677600'
            Sunset:
              description: Timestamp when endpoint will no longer be available
              schema:
                type: string
              example: 'Sun, 31 Dec 2025 23:59:59 GMT'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '409':
          $ref: '#/components/responses/409'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      security:
        - Client:
            - 'bcm:configuration:write'
      x-stoplight:
        id: unzah9z5zgpy5
  '/ownerships/{moduleId}':
    delete:
      deprecated: true
      summary: Waive ConnectModule ownership
      operationId: delete-ownership-moduleid
      description: Waives ownership of a ConnectModule providing the `moduleId` as path parameter. Additionally all enabled features will be disabled.
      tags:
        - ConnectModule Ownerships
      parameters:
        - $ref: '#/components/parameters/moduleId'
      responses:
        '204':
          description: No Content
          headers:
            Deprecation:
              description: UTC time when deprecation was announced
              schema:
                type: string
              example: '@1756677600'
            Sunset:
              description: Timestamp when endpoint will no longer be available
              schema:
                type: string
              example: 'Sun, 31 Dec 2025 23:59:59 GMT'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '409':
          $ref: '#/components/responses/409'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      security:
        - Client:
            - 'bcm:configuration:write'
      x-stoplight:
        id: jgifi2t78318u
components:
  schemas:
    ConnectModule:
      title: ConnectModule
      type: object
      required:
        - id
        - bikeId
        - oemBikeId
        - oemBrandId
        - createdAt
        - updatedAt
        - syncedAt
        - syncStatus
        - features
      properties:
        id:
          type: string
          description: BCM unique identifier. Combination of `productCode` _ `partNumber` _ `serialNumber`.
          example: BCM3100_EB1310000B_17918-0052-01-368-00-0000
          readOnly: true
        bikeId:
          type: string
          description: Bosch unique eBike ID.
          format: uuid
          example: 7255dccf-c929-41f7-9aa6-a043f6096e19
          readOnly: true
        oemBikeId:
          type: string
          description: OEM unique eBike ID.
          maxLength: 30
          minLength: 1
          example: ZMFPKXJ9Y6ZRSTW4
          readOnly: true
        oemBrandId:
          type: string
          description: OEM brand identifier.
          minLength: 1
          maxLength: 30
          example: YOUR-BRAND
          readOnly: true
        createdAt:
          type: string
          format: date-time
          example: '2023-03-01T14:31:00.002Z'
          description: Timestamp when the configuration was created in the cloud.
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          example: '2023-03-05T14:31:00.002Z'
          description: Timestamp when the configuration was updated in the cloud.
          readOnly: true
        syncedAt:
          type: string
          format: date-time
          description: Timestamp when the configuration was applied on the ConnectModule.
          example: '2023-03-01T14:31:00.002Z'
          readOnly: true
        syncStatus:
          type: string
          enum:
            - PENDING
            - SUCCESS
            - WARNING
            - ERROR
          default: SUCCESS
          description: |-
            Indicates the synchronization status of the configuration between the cloud and the ConnectModule.
            - PENDING -> Current configuration not yet synchronized with the ConnectModule.
            - SUCCESS -> Successfully applied all feature configurations on the ConnectModule.
            - WARNING -> Configuration was applied on the ConnectModule, but there was a warning for at least one feature configuration.
            - ERROR -> Configuration was applied on the ConnectModule, but there was an error for at least one feature configuration.
          readOnly: true
        features:
          type: array
          items:
            $ref: '#/components/schemas/Feature'
      x-stoplight:
        id: c9b4uhk0iavee
    ConnectModuleMaster:
      title: ConnectModuleMaster
      type: object
      required:
        - moduleId
        - bikeId
      properties:
        moduleId:
          type: string
          example: BCM3100_EB1310000B_17918-0052-01-368-00-0000
          description: BCM unique identifier. Combination of `productCode` _ `partNumber` _ `serialNumber`.
        bikeId:
          type: string
          format: uuid
          example: 476526c4-e28a-4dea-976c-c7d01aede23d
          description: Bosch unique eBike ID.
      x-stoplight:
        id: ahr7cvvmt4sqh
    Feature:
      title: Feature
      type: object
      additionalProperties: false
      required:
        - type
        - status
        - requestedProfile
        - appliedProfile
        - updatedAt
      properties:
        type:
          type: string
          x-extensible-enum:
            - value: LOCATION_TRACKING
            - value: BIKE_STATUS
            - value: DISABLE_MOTOR_SUPPORT
          description: Type of feature.
          readOnly: true
        status:
          type: string
          enum:
            - PENDING
            - ENABLED
            - DISABLED
          description: |-
            Indicates the synchronization status of the feature configuration between the cloud and the ConnectModule.
            - PENDING -> Current configuration not yet synchronized with the ConnectModule
            - ENABLED -> Successfully applied requested feature profile on the ConnectModule
            - DISABLED -> No feature profile set
          default: DISABLED
          readOnly: true
        statusDetail:
          type: object
          required:
            - type
          properties:
            type:
              enum:
                - WARNING
                - ERROR
              description: |-
                - WARNING -> Please update ConnectModule software to get feature support or updates.
                - ERROR -> An internal error occurred on the ConnectModule.
          readOnly: true
        requestedProfile:
          type: string
          x-extensible-enum:
            - value: NONE
            - value: DEFAULT
            - value: CHARGING
          description: The requested feature profile.
          default: NONE
          maxLength: 30
          minLength: 1
        appliedProfile:
          type: string
          x-extensible-enum:
            - value: NONE
            - value: DEFAULT
            - value: CHARGING
          description: The last known feature profile applied on the ConnectModule.
          example: NONE
          maxLength: 30
          minLength: 1
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the feature configuration was updated in the cloud.
          example: '2023-03-05T14:31:00.002Z'
          readOnly: true
      x-stoplight:
        id: b5z35ulvgi481
    Problem:
      type: object
      title: Problem
      required:
        - type
        - detail
        - requestId
      properties:
        type:
          type: string
          format: uri-reference
          description: |
            A URI reference that uniquely identifies the problem type only in the context of the provided API. Opposed to the specification in RFC-7807, it is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
          default: 'about:blank'
          example: /some/uri-reference
        title:
          type: string
          description: |
            A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
          example: some title for the error situation
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
          example: some description for the error situation
        instance:
          type: string
          format: uri-reference
          description: |
            A URI reference that identifies the specific occurrence of the problem, e.g. by adding a fragment identifier or sub-path to the problem type. May be used to locate the root of this problem in the source code.
          example: /some/uri-reference#specific-occurrence-context
        requestId:
          type: string
          description: ID for this request.
          example: 075be661d3a4460b98dee5d66849dd5e
      x-stoplight:
        id: 2prx4gai30znp
  securitySchemes:
    Client:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://p9.authz.bosch.com/auth/realms/obc/protocol/openid-connect/token'
          refreshUrl: 'https://p9.authz.bosch.com/auth/realms/obc/protocol/openid-connect/token'
          scopes:
            'bcm:configuration:write': Enables read and update operations.
      description: Bosch Identity & Access Management
  responses:
    '400':
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    '401':
      description: Unauthorized
      content:
        text/plain:
          schema:
            type: string
          examples:
            access-token-expired:
              value: JWT is expired
            access-token-validation-failed:
              value: JWT verification fails
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    '403':
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    '404':
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples:
            generic:
              value:
                type: /problems/not-found
                title: Not Found
                status: 404
                detail: No data found for provided id.
                requestId: 4461cda00a2340bba5c0c4296e4f25fb
            ambiguous-identifier:
              value:
                type: /problems/not-found
                title: Not Found
                status: 404
                detail: Multiple resources were found for the given `OEM_BIKE_ID`. Please use `BIKE_ID` to disambiguate.
                instance: /problems/not-found#ambiguous-identifier
                requestId: 3f71f4a8e9894630942a486158f95162
    '409':
      description: Conflict
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples:
            ownership-claim-conflict:
              value:
                type: /problems/ownership-claim-conflict
                title: Ownership claim conflict
                status: 409
                detail: Cannot claim ownership for module with id moduleId
                requestId: 3f71f4a8e9894630942a486158f95162
            ownership-waive-conflict:
              value:
                type: /problems/ownership-waive-conflict
                title: Ownership waive conflict
                status: 409
                detail: Cannot waive ownership for module with id moduleId. Device has no owner.
                requestId: 3f71f4a8e9894630942a486158f95162
    '429':
      description: Too Many Requests
      headers:
        X-RateLimit-Limit:
          description: 'Bucket size, refresh size and time window for refresh in seconds'
          schema:
            type: string
          example: '100, 100;w=60'
        X-RateLimit-Reset:
          description: Time in seconds until bucket is refreshed
          schema:
            type: integer
          example: 57
    '500':
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    default:
      description: Example response
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
  parameters:
    moduleId:
      name: moduleId
      in: path
      required: true
      schema:
        type: string
        example: BCM3100_EB1310000B_17918-0052-01-368-00-0000
      description: BCM unique identifier. Combination of `productCode` _ `partNumber` _ `serialNumber`.
